<?php
session_start();
require('assets/fpdf/fpdf.php');
$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AddPage();
$pdf->Image('assets/image/logo1.png', 8, 13, 30);
$pdf->Image('assets/image/hima.png', 172, 13, 30);
$pdf->SetFont('Times', 'B', 17);
$pdf->Cell(190, 0, $_POST['judulsurat'], 0, 0, 'C');
$pdf->Ln(3);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(190, 6, 'HIMPUNAN MAHASISWA TEKNOLOGI INFORMASI', 0, 0, 'C');
$pdf->Ln();
$pdf->SetTextColor(0, 200, 255);
$pdf->Cell(190, 6, 'FAKULTAS SAINT DAN TEKNOLOGI', 0, 0, 'C');
$pdf->Ln();
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(190, 6, 'UNIVERSITAS ISLAM NEGERI AR-RANIRY', 0, 0, 'C');
$pdf->Ln();
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(190, 6, 'Sekretariat: Komplek Fakultas Saints Dan Teknologi', 0, 0, 'C');
$pdf->Ln();
$pdf->Cell(190, 6, 'No. Telp: +6285261506337 - Email: hima.ti@ar-raniry.ac.id', 0, 0, 'C');
$pdf->Ln(10);
$pdf->Cell(190, 0.5, '', '0', '1', 'C', true);
$pdf->Ln(1);
$pdf->Cell(190, 0.3, '', '0', '1', 'C', true);
$pdf->Ln(3);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(20, 6, 'Nomor', 0, 0, 'L');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(90, 6, $_POST['nomorsurat'], 0, 0, 'L');
$pdf->Cell(0, 6, $_POST['tanggalsurat'], 0, 0, 'R');
$pdf->Ln(6);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(20, 6, 'Lampiran', 0, 0, 'L');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(90, 6, $_POST['lampiran'], 0, 0, 'L');
$pdf->Ln(6);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(20, 6, 'Perihal', 0, 0, 'L');
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(90, 6, $_POST['perihal'], 0, 0, 'L');
$pdf->SetMargins(13, 0, 0);
$pdf->Ln(13);
$pdf->Cell(100, 6, 'Kepada Yth.', 0, 0, 'L');
$pdf->Ln(10);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(100, 6, $_POST['tujuansurat'], 0, 0, 'L');
$pdf->Ln(6);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(100, 6, 'Di-Tempat', 0, 0, 'L');
$pdf->Ln(9);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(100, 6, 'Assalamualaikum Wr. Wb', 0, 0, 'L');
$pdf->Ln(9);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(100, 6, 'Dengan Hormat,', 0, 0, 'L');
$html = '      ' . $_POST['isisurat'];
$pdf->Ln(7);
$pdf->SetFont('Arial', '', 10);
$pdf->MultiCell(190, 7, $html, 0, 'J');
$pdf->Ln(3);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(25, 6, 'Hari / Tanggal', 0, 0, 'L');
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(100, 6, $_POST['haritanggal'], 0, 0, 'L');
$pdf->Ln(7);
$pdf->Cell(25, 6, 'Waktu', 0, 0, 'L');
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(100, 6, $_POST['waktu'], 0, 0, 'L');
$pdf->Ln(7);
$pdf->Cell(25, 6, 'Via', 0, 0, 'L');
$pdf->Cell(5, 6, ':', 0, 0, 'L');
$pdf->Cell(100, 6, $_POST['via'], 0, 0, 'L');
$pdf->Ln(10);
$pdf->Cell(190, 6, '       Demikian surat ini kami sampaikan, atas perhatian dan kesedian bapak kami ucapkan terimakasih.', 0, 0, 'L');
$pdf->Ln(8);
$pdf->SetFont('Arial', 'I', 10);
$pdf->Cell(100, 6, 'Wassalamualaikum Wr. Wb', 0, 0, 'L');
$pdf->Ln(10);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(180, 6, 'Hormat Kami', 0, 0, 'C');
$pdf->SetMargins(30, 0, 10);
$pdf->Ln(10);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(120, 6, 'Ketua Panitia', 0, 0, 'L');
$pdf->Cell(30, 6, 'Sekretaris Panitia', 0, 0, 'L');
$pdf->Ln(17);
$pdf->Cell(120, 6, $_POST['ketuapanitia'], 0, 0, 'L');
$pdf->Cell(30, 6, $_POST['sekpanitia'], 0, 0, 'L');
$pdf->Ln(5);
$pdf->Cell(120, 6, 'Nim.' . $_POST['nimketua'], 0, 0, 'L');
$pdf->Cell(30, 6, 'Nim.' . $_POST['nimsek'], 0, 0, 'L');

$pdf->SetMargins(8, 0, 10);
$pdf->Ln(13);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(190, 6, 'Mengetahui', 0, 0, 'C');
$pdf->Ln(6);
$pdf->Cell(190, 6, 'Ketua Himpunan Mahasiswa Teknologi Informasi', 0, 0, 'C');
$pdf->Ln(6);
$pdf->Cell(190, 6, 'Fakultas Sains dan Teknologi, UIN Ar-Raniry', 0, 0, 'C');
$pdf->Ln(6);
$pdf->Cell(190, 6, 'Periode 2020/2021', 0, 0, 'C');
$pdf->Ln(18);
$pdf->Cell(190, 6, $_POST['kahim'], 0, 0, 'C');
$pdf->Ln(6);
$pdf->Cell(190, 6, 'Nim.' . $_POST['nimkahim'], 0, 0, 'C');







$pdf->Output();
